name: Flutter Build APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set Java version to 17
          distribution: 'temurin'  # Specify the distribution

      # Step 3: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Step 4: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Generate localization files
      - name: Generate localization files
        run: flutter gen-l10n

      # Step 6: Run build_runner to generate files
      - name: Build with build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      # Step 7: Build APK (Android)
      - name: Build APK (Android)
        run: flutter build apk --release

      # Step 8: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
